baseURL = 'https://bigeatie.com'
languageCode = 'en-us'
title = "BigEatie's Blog"
theme = "hugo-xmin"
[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'tango'
    tabWidth = 4


[[menu.main]]
name = "Home"
url = ""
weight = 1

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 4

[[menu.main]]
name = "Subscribe"
url = "index.xml"