#+TITLE: TikZ Images in Org-Preview
#+hugo_base_dir: ../
#+hugo_tags: Emacs OrgMode LaTeX
#+DATE: <2024-09-14 Thu>

If you use LaTeX within org-mode you may come across a situation where you would like to embed TikZ diagrams and have Emacs preview them with ~org-latex-preview~. Unfortunately Emacs does not do this very well out of the box. I don't fully understand why. At least [[https://www.reddit.com/r/orgmode/comments/xxabty/TikZ_circuits_not_showing_in_orglatexpreview/irbd255/][one reddit comment]] suggests that this is because the default program used to generate LaTeX previews, dvipng, does not work well with TikZ. Fortunately, it seems like dvisvgm does work nicely with TikZ. Once you have that installed, dropping the following snippet into your config should get LaTeX previews working.

#+BEGIN_SRC elisp
  (setq org-preview-latex-process-alist
        '((dvisvgm :programs ("latex" "dvisvgm")
                   :description "dvi > svg"
                   :message "you need to install the programs: latex and dvisvgm."
                   :image-input-type "dvi"
                   :image-output-type "svg"
                   :image-size-adjust (1.7 . 1.5)
                   :latex-compiler ("latex -interaction nonstopmode -output-directory %o %f")
                   :image-converter ("dvisvgm %f -n -b min -c %S --currentcolor -o %O"))))

  (setq org-latex-packages-alist
        '(("" "tikz" t)         
          ("" "tikz-cd" t)))

  (setq org-latex-create-formula-image-program 'dvisvgm)
#+END_SRC

The ~image-size-adjust~ parameters above work well for me, but feel free to adjust to your liking, of course.

You can test whether the preview works now. If you need a snippet to test, you can use the following.

#+BEGIN_SRC
\begin{tikzcd}
F \arrow[r] & E \arrow[d, "\pi"] \\
            & M
\end{tikzcd}
#+END_SRC

Here's a video showing how both the before and after of this snippet should look.

[[file:./images/TikzPreview.mp4]]
